export const LANGUAGES = [
    { code: 'bg', label: 'Български', countryCode: 'BG' },
    { code: 'cs', label: 'Čeština', countryCode: 'CZ' },
    { code: 'da', label: 'Dansk', countryCode: 'DK' },
    { code: 'de', label: 'Deutsch', countryCode: 'DE' },
    { code: 'et', label: 'Eesti', countryCode: 'EE' },
    { code: 'en', label: 'English', countryCode: 'GB' },
    { code: 'sp', label: 'Español', countryCode: 'ES' },
    { code: 'fr', label: 'Français', countryCode: 'FR' },
    { code: 'ga', label: 'Gaeilge', countryCode: 'IE' },
    { code: 'hr', label: 'Hrvatski', countryCode: 'HR' },
    { code: 'is', label: 'Íslenska', countryCode: 'IS' },
    { code: 'it', label: 'Italiano', countryCode: 'IT' },
    { code: 'lb', label: 'Lëtzebuergesch', countryCode: 'LU' },
    { code: 'lv', label: 'Latviešu', countryCode: 'LV' },
    { code: 'lt', label: 'Lietuvių', countryCode: 'LT' },
    { code: 'nl', label: 'Nederlands', countryCode: 'NL' },
    { code: 'no', label: 'Norsk', countryCode: 'NO' },
    { code: 'pl', label: 'Polski', countryCode: 'PL' },
    { code: 'pt', label: 'Português', countryCode: 'PT' },
    { code: 'ro', label: 'Română', countryCode: 'RO' },
    { code: 'sk', label: 'Slovenčina', countryCode: 'SK' },
    { code: 'sl', label: 'Slovenščina', countryCode: 'SI' },
    { code: 'fi', label: 'Suomi', countryCode: 'FI' },
    { code: 'sv', label: 'Svenska', countryCode: 'SE' },
    { code: 'uk', label: 'Українська', countryCode: 'UA' },
    { code: 'el', label: 'Ελληνικά', countryCode: 'GR' },
];
